### ISSUE TITLE
【最終課題】マイページの作成

### ISSUE THREAD

**Issue by tak848** [shinonome-inc/mobile_tak848#18]
* マイページ
  * ログイン画面での認証機能
  * 認証したユーザーの情報表示
  * フォロー・フォロワーリストへの遷移
  * ページネーション実装

**Comment by TAK848** [comment]
Swiftで配列をjoin(結合)して文字列にする方法 | Swift5 入門書-逆引き大全集
https://swift.tecc0.com/?p=160
